# Generated by Django 3.0.2 on 2020-01-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unitCost', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('imgName', models.CharField(default='', max_length=50)),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('saleTax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shippingTotal', models.IntegerField(default=0)),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequenceNumber', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('orderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('partNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Part')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerState',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Customer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.State')),
            ],
        ),
    ]
